export const Zkdata = [
    { name: "Mav", link: 'https://app.mav.xyz/', icon: '/static/images/mylogo/mav.png' },
    { name: 'SyncSwap', link: 'https://syncswap.xyz/', color: `#74f763`, icon: '/static/images/mylogo/syncswap.png' },
    { name: 'SpaceFi', link: 'https://app.spacefi.io/#/home', icon: '/static/images/mylogo/spacefi.png' },
    { name: 'Satis', link: 'https://sat.is/', icon: '/static/images/mylogo/sat.png' },
    { name: 'ZkSync(Velocore)', link: 'https://zksync.velocore.xyz/swap', color: `#74f763`, icon: '/static/images/mylogo/velocore.png' },
    { name: 'Izumi', link: 'https://izumi.finance/trade/swap', icon: '/static/images/mylogo/izumi.png' },
    { name: 'Mute', link: 'https://app.mute.io/swap', icon: '/static/images/mylogo/mute.png' },
    { name: 'Trade SyncFutures', link: 'https://trade.synfutures.com/', color: `#74f763`, },
    { name: 'Eralend', link: 'https://app.eralend.com/', icon: '/static/images/mylogo/era.png' },
    { name: 'Xy Finance', link: 'https://app.xy.finance/', icon: '/static/images/mylogo/xy.png' },
    { name: 'Deri', link: 'https://deri.io/#/pro/trade/futures/BTCUSD', icon: '/static/images/mylogo/deri.png' },
    { name: 'OpenOcean Finance', link: 'https://app.openocean.finance/classic', color: `#74f763`, icon: '/static/images/mylogo/openocean.png' },
    { name: 'Zerolend', link: 'https://app.zerolend.xyz/', risk: true, color: `#f7f757`, icon: '/static/images/mylogo/zerolend.png' },
    { name: 'Interport', link: 'https://app.interport.fi/324/324/ETH/USDC', color: `#74f763`, icon: '/static/images/mylogo/interport.svg' },
    { name: 'Onchain Trade', link: 'https://onchain.trade/', icon: '/static/images/mylogo/onchain.svg' },
    { name: 'Unidex Exchange', link: 'https://www.unidex.exchange/', icon: '/static/images/mylogo/unidex.svg' },
    { name: 'Zkswap Finance', link: 'https://zkswap.finance/', icon: '/static/images/mylogo/zkswap.png' },
    { name: 'Zkera', link: 'https://zkera.fi/', risk: true, color: `#f7f757`, icon: '/static/images/mylogo/zkera.svg' },
    { name: 'Mesprotocol', link: 'https://www.mesprotocol.com/', risk: true, color: `#f7f757`, icon: '/static/images/mylogo/mes.png' },
    { name: 'Domani Finance', link: 'https://domani.finance/', risk: true, color: `#f7f757`, icon: '/static/images/mylogo/Domani_logo_white.png' },
    { name: 'Symbiosis Finance', link: 'https://app.symbiosis.finance/', color: `#74f763`, icon: '/static/images/mylogo/symbosis.png' },
    { name: 'Xbank Finance', link: 'https://www.xbank.finance/', color: `#f7f757`, icon: '/static/images/mylogo/xbank.png' },
    { name: 'Zkdx', link: 'https://zkdx.io/', icon: '/static/images/mylogo/zkdx.png' },
    { name: 'Satori Finance', link: 'https://satori.finance/', icon: '/static/images/mylogo/satori.svg' },
    { name: 'Hold Station', link: 'https://holdstation.com/', color: `#74f763` },
    { name: 'Fi Woo', link: 'https://fi.woo.org/', icon: '/static/images/mylogo/woo.png' },
    { name: 'Vesync Finance', link: 'https://app.vesync.finance/swap', icon: '/static/images/mylogo/vs_logo.svg' },
    { name: 'Rollup Finance', link: 'https://www.rollup.finance/', icon: '/static/images/mylogo/rollup.png' },
    { name: 'Reactor Fusion', link: 'https://reactorfusion.xyz/', risk: true, color: `#f7f757` },
    { name: 'Tavaera', link: 'https://tevaera.com/', icon: '/static/images/mylogo/tecaera.png' },
    { name: 'Crypto Maze', link: 'https://cryptomaze.app/', color: `#74f763` },
    { name: 'TinyWorlds', link: 'https://tinyworlds.io/' },
    { name: 'Robots Farm', link: 'https://robots.farm/', risk: true, color: `#f7f757` },
    { name: 'Galaxyblitz World', link: 'https://galaxyblitz.world/', color: `#74f763` },
    { name: 'The Snkrz', link: 'https://www.thesnkrz.com/', icon: '/static/images/mylogo/SNKRZ.png' },
    { name: 'Bladedao Game', link: 'https://www.bladedao.games/', risk: true, color: `#f7f757` },

]
